language: haxe
sudo: required

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "4.0.0-rc.2"

install:
  # Install dependencies
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib install flixel-addons
  - haxelib git lycan https://github.com/JoeCreates/Lycan
  - haxelib git MacroTween https://github.com/JoeCreates/MacroTween
  - haxelib list

script:
  - haxelib run openfl build "Project.xml" flash
  - haxelib run openfl build "Project.xml" html5
  #- haxelib run openfl build "Project.xml" linux

# Deploy generated demo to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/export/html5/bin
  github_token: $GITHUB_API_KEY
  # Only deploy for one of the Haxe builds
  on:
    condition: "$TRAVIS_HAXE_VERSION = 4.0.0-rc.2"
    branch: master