language: haxe
sudo: required

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "4.0.0-preview.5"

install:
  # Install dependencies
  - haxelib install openfl
  - haxelib install flixel
  # Grab the latest macrotween from GitHub
  - mkdir macrotween_repo_clone
  - pushd macrotween_repo_clone
  - git clone --branch=master https://github.com/JoeCreates/MacroTween .
   # Package the haxelib
  - chmod +x ./package_haxelib.sh
  - ./package_haxelib.sh
  # Install haxelib locally
  - haxelib install MacroTween.zip
  - popd
  - haxelib list

script:
  - haxelib run openfl build "Project.xml" flash
  - haxelib run openfl build "Project.xml" html5
  #- haxelib run openfl build "Project.xml" linux
  - ls -a

# Deploy generated demo to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/export/html5/bin
  github_token: $GITHUB_API_KEY
  # Only deploy for one of the Haxe builds
  on:
    condition: "$TRAVIS_HAXE_VERSION = 4.0.0-preview.5"
    branch: master