language: haxe
sudo: required

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "4.0.0-preview.5"

install:
  # Install dependencies
  - haxelib install flixel
  - haxelib install macrotween
  - haxelib list

script:
  - haxelib run openfl build "Project.xml" flash
  - haxelib run openfl build "Project.xml" html5
  - haxelib run openfl build "Project.xml" linux